### ISSUE TITLE
ESP8266 can't connect to parse-server

### ISSUE THREAD

**Issue by Pietroga** [ParsePlatform/Parse-SDK-Arduino#11]
I've tried to connect to my parse-server with an ESP8266 by settings:

`const char* PARSE_API = "xx.xx.xx.xxx:1337/parse";`
`const char* PARSE_API = "xx.xx.xx.xxx:1337";`
`const char* PARSE_API = "xx.xx.xx.xxx:1337/parse/";`
`const char* PARSE_API = "http:xx.xx.xx.xxx:1337/parse";`

Can you tell me what I'm doing wrong?
Thanks

**Comment by waqas-ogc** [comment]
Could you solve the issue ? I'm also working on to connect ESP8266 with custom server and looking for some example.

**Comment by rafaalvfe** [comment]
@Pietroga @waqas-ogc did anyone found the solution to this?

**Comment by Pietroga** [comment]
@rafaalvfe now I'm using the normal http request REST API
