### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by andreipopa1002** [ParsePlatform/Parse-SDK-Arduino#21]
Hi all,
I am trying to use the SDK for my personal project and it fails to compile.

this is a snippet to for the error: 
`In file included from .pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseInternal.h:5,
                 from .pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseObjectUpdate.cpp:22:
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseUtils.h: In static member function 'static int ParseUtils::getStringFromJSON(const char*, const char*, char*, int)':
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseUtils.h:51:9: warning: unused variable 'escape' [-Wunused-variable]
   51 |     int escape = 0;
      |         ^~~~~~
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseUtils.h: In static member function 'static bool ParseUtils::isSanitizedString(const String&)':
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseUtils.h:240:18: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
  240 |     for(k = 0; k < userData.length(); k++) {
      |                ~~^~~~~~~~~~~~~~~~~~~
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseUtils.h:241:20: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'unsigned int'} [-Wsign-compare]
  241 |       for(i = 0; i < strlen(badChars); i++) {
      |                  ~~^~~~~~~~~~~~~~~~~~
In file included from .pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseClient.h:28,
                 from .pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseObjectUpdate.cpp:23:
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseResponse.h: At global scope:
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseResponse.h:54:3: error: 'ConnectionClient' does not name a type
   54 |   ConnectionClient* client;
      |   ^~~~~~~~~~~~~~~~
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseResponse.h:71:33: error: expected ')' before '*' token
   71 |   ParseResponse(ConnectionClient* client);
      |                ~                ^
      |                                 )
In file included from .pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseClient.h:29,
                 from .pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseObjectUpdate.cpp:23:
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParsePush.h:38:29: error: expected ')' before '*' token
   38 |   ParsePush(ConnectionClient* pushClient);
      |            ~                ^
      |                             )
In file included from .pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseObjectUpdate.cpp:23:
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseClient.h:46:3: error: 'ConnectionClient' does not name a type
   46 |   ConnectionClient client;
      |   ^~~~~~~~~~~~~~~~
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseClient.h:47:3: error: 'ConnectionClient' does not name a type
   47 |   ConnectionClient pushClient;
      |   ^~~~~~~~~~~~~~~~
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseClient.h:51:13: error: 'ConnectionClient' has not been declared
   51 |   void read(ConnectionClient* client, char* buf, int len);
      |             ^~~~~~~~~~~~~~~~
In file included from .pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseInternal.h:5,
                 from .pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseQuery.cpp:22:
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseUtils.h: In static member function 'static int ParseUtils::getStringFromJSON(const char*, const char*, char*, int)':
.pio/libdeps/nodemcuv2/Parse Arduino SDK/src/internal/ParseUtils.h:51:9: warning: unused variable 'escape' [-Wunused-variable]
   51 |     int escape = 0;`

Any help would be greatly appreciated. Thank you!

**Comment by mikdanjey** [comment]
Please resolve this as soon as possible.

**Comment by mtrezza** [comment]
Please see the [README](https://github.com/parse-community/Parse-SDK-Arduino#readme):

> WARNING ⚠ - this project has been retired due to lack of use & contribution, if you wish to continue to use it please fork or if you wish to maintain this project make yourself known

**Comment by garudaonekh** [comment]
Here for ESP32,
https://github.com/garudaonekh/Parse-Platforrm-SDK-for-ESP32

Note: not all features are tested yet
