### ISSUE TITLE
set InstallationId failed

### ISSUE THREAD

**Issue by garudaonekh** [ParsePlatform/Parse-SDK-Arduino#22]
Hi,
I managed to get this working on ESP32 after several fix. I can create object, read,write.

But set new InstallationId failed. I think maybe the parse server have changed since this last updated.

So **POST /1/installations** not work anymore

I got this error:

```
16:19:15.285 -> POST /parse/1/installations HTTP/1.1
16:19:15.285 -> Host: io.agrokh.com
16:19:15.285 -> X-Parse-Client-Version: 1.0.3
16:19:15.285 -> X-Parse-Application-Id: any-random-number-of-strings
16:19:18.710 -> X-Parse-Client-Key: kjlsfkjlsfjh
16:19:18.710 -> X-Parse-Installation-Id: e9ce0a83-4a8f-7a4f-8c31-f2f986769681
16:19:18.710 -> Content-Type: application/json; charset=utf-8
16:19:18.710 -> Content-Length: 109
16:19:18.710 -> Connection: close
16:19:18.710 -> 
16:19:18.710 -> {"installationId": "e9ce0a83-4a8f-7a4f-8c31-f2f986769681", "deviceType": "embedded", "parseVersion": "1.0.0"}response:<!DOCTYPE html>
16:19:18.710 -> <html lang="en">
16:19:18.710 -> <head>
16:19:18.710 -> <meta charset="utf-8">
16:19:18.710 -> <title>Error</title>
16:19:18.710 -> </head>
16:19:18.710 -> <body>
16:19:18.710 -> <pre>Cannot POST /parse/1/in

```

**Comment by garudaonekh** [comment]
Ok, remove 1 from the url, it works.

POST /parse/1/installations ==> POST /parse/installations

**Comment by mtrezza** [comment]
@garudaonekh This SDK has not seen much maintenance in the past. Let us know your experience with the SDK and please feel free to open any issues you may find.

**Comment by garudaonekh** [comment]
> @garudaonekh This SDK has not seen much maintenance in the past. Let us know your experience with the SDK and please feel free to open any issues you may find.

I have used Parse since many years ago for mobile app. I move to Back4App a few years ago..

But now I switch to iOT projects. I decide to host Parse Server myself on DigitalOcean. As of now, It works flawlessly with ESP32. I will upload this Parse-SDK-Arduino update for ESP32 after I check every features.

Thanks;

**Comment by garudaonekh** [comment]
Hi, I create a repos for it here
https://github.com/garudaonekh/Parse-Platforrm-SDK-for-ESP32

**Comment by mtrezza** [comment]
Would it make sense that you open PRs to this repository so we can fix the issues? This repository is not maintained, but if you would like to bring it up to date we's be happy to review your PRs.

**Comment by mtrezza** [comment]
@garudaonekh Would it make sense that you open PRs to this repository so we can fix the issues? This repository is not officially maintained, but if you would like to fix a bug or add a new feature (like MAC address as installation ID) we'd be happy to review your PRs.

Unfortunately I had to remove your other comments. It's against our policy to advertise 3rd party repositories. Developers can find the latest forks (incl. yours) in the GitHub network graph of this repository.

**Comment by garudaonekh** [comment]
> @garudaonekh Would it make sense that you open PRs to this repository so we can fix the issues? This repository is not officially maintained, but if you would like to fix a bug or add a new feature (like MAC address as installation ID) we'd be happy to review your PRs.
> 
> Unfortunately I had to remove your other comments. It's against our policy to advertise 3rd party repositories. Developers can find the latest forks (incl. yours) in the GitHub network graph of this repository.

Sorry, I just use github repos. I do not know how to update via PRS. That is why I create new and drop code there

**Comment by mtrezza** [comment]
Got it. We have a [blog article](https://blog.parseplatform.org/learn/tutorial/community/nodejs/2021/02/14/How-to-start-contributing-to-Parse-Server.html) that is especially directed towards first time contributors and a more technical [Contribution Guide](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md). They are for the Parse Server repository, but the steps are similar for this repository.
